In [ ]:
import pandas as pd
import numpy as np

In [ ]:
crop_train=pd.read_csv("Crop_recommendation_train.csv")
crop_test = pd.read_csv("Crop_recommendation_test.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'Crop_recommendation_train.csv'

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
crop_train

N   P   K  temperature   humidity        ph    rainfall        label
0      37  64  22    17.481897  18.825197  5.954665  121.940137  kidneybeans
1      70  54  46    39.731491  91.122206  6.919342  122.762865       papaya
2      94  39  18    23.891146  57.487758  5.893093  102.830194        maize
3      99  29  55    29.193787  91.462411  6.660955   26.482403    muskmelon
4       9  21  32    32.269353  53.560928  5.870116   95.940354        mango
...   ...  ..  ..          ...        ...       ...         ...          ...
1754   83  11  53    29.540972  92.917783  6.163921   21.965308    muskmelon
1755  110   7  45    26.638386  84.695469  6.189214   48.324286   watermelon
1756   84  37  42    25.496748  81.134491  6.691074  169.928823         jute
1757   74  39  38    23.241135  84.592018  7.782051  233.045345         rice
1758   85  33  25    26.208114  52.509880  6.910824  189.094482       coffee

[1759 rows x 8 columns]

In [ ]:
#x input, y target
x_train = crop_train.drop('label',axis=1)
y_train = crop_train['label']

x_test = crop_test.drop('label',axis=1)
y_test = crop_test['label']


y_test

0           rice
1      muskmelon
2          maize
3           jute
4        coconut
         ...    
436        mango
437      coconut
438         jute
439        maize
440        apple
Name: label, Length: 441, dtype: object

In [ ]:
#training svm kernel 'linear','poly','rbf','sigmoid'
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
svclassifier = SVC(kernel='linear')

svclassifier.fit(x_train,y_train)
y_pred = svclassifier.predict(x_test)


In [ ]:
#evaluate SVM accuracy performance
from sklearn.metrics import classification_report,confusion_matrix

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
score = accuracy_score(y_test,y_pred)
score

[[28  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 19  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 19  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 23  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 20  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 23  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 16  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  1  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0 19  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 16  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0  0  0  0 21  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 16  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  0 14  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0

0.9682539682539683

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
#x is input, y is target
knn_crop = KNeighborsClassifier(n_neighbors=10)
knn_crop.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=10)

In [ ]:
y_pred = knn_crop.predict(x_test)

In [ ]:
accuracy= accuracy_score(y_test,y_pred)
accuracy

0.963718820861678

In [ ]:
#Decission tree
from sklearn.tree import DecisionTreeClassifier

In [ ]:
#create model
model = DecisionTreeClassifier()
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [ ]:
y_preds=model.predict(x_test)

In [ ]:
accuracy= accuracy_score(y_test,y_preds)
accuracy

0.9841269841269841

In [ ]:
#N - ratio of Nitrogen content in soil
#P - ratio of Phosphorous content in soil
#K - ratio of Potassium content in soil
#temperature - temperature in degree Celsius
#humidity - relative humidity in %
#ph - ph value of the soil
#rainfall - rainfall in mm